#!/bin/bash

# 🚚 TruK - Manual Installation Guide
# Execute este script passo a passo

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  🚚 TruK - Virtual Trucking Company Manager             ║"
echo "║  Guia de Instalação Manual                              ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

echo "📋 REQUISITOS:"
echo "   • Python 3.10+"
echo "   • pip ou apt para instalar pacotes"
echo ""

echo "⚠️  ATENÇÃO:"
echo "   Seu sistema não tem pip3 instalado."
echo "   Você precisa instalar os pacotes Python de uma das formas abaixo:"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo "OPÇÃO 1: Instalar pip3 (Recomendado)"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "sudo apt update"
echo "sudo apt install python3-pip python3-venv"
echo ""
echo "Depois execute novamente: ./setup.sh"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo "OPÇÃO 2: Instalar pacotes via apt (Ubuntu/Debian)"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "sudo apt update"
echo "sudo apt install python3-django python3-psycopg2 python3-pil"
echo ""
echo "# Depois instalar pacotes adicionais manualmente:"
echo "wget https://bootstrap.pypa.io/get-pip.py"
echo "python3 get-pip.py --user"
echo "~/.local/bin/pip3 install --user python-decouple django-htmx django-widget-tweaks plotly pandas whitenoise gunicorn"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo "OPÇÃO 3: Criar ambiente virtual (Mais limpo)"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "# Instalar python3-venv"
echo "sudo apt install python3.12-venv"
echo ""
echo "# Criar ambiente virtual"
echo "cd /home/daniel/dev/truk"
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo ""
echo "# Instalar get-pip no venv"
echo "wget https://bootstrap.pypa.io/get-pip.py"
echo "python get-pip.py"
echo ""
echo "# Instalar dependências"
echo "pip install -r requirements.txt"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo "APÓS INSTALAR AS DEPENDÊNCIAS:"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "1. Executar migrações:"
echo "   python3 manage.py migrate"
echo ""
echo "2. Criar superusuário:"
echo "   python3 manage.py createsuperuser"
echo ""
echo "3. Coletar arquivos estáticos:"
echo "   python3 manage.py collectstatic --noinput"
echo ""
echo "4. Rodar servidor:"
echo "   python3 manage.py runserver"
echo ""
echo "5. Acessar:"
echo "   http://localhost:8000"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo "COMANDOS ÚTEIS:"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "# Verificar versão Python"
echo "python3 --version"
echo ""
echo "# Verificar se Django está instalado"
echo "python3 -c 'import django; print(django.VERSION)'"
echo ""
echo "# Listar pacotes instalados"
echo "python3 -m pip list 2>/dev/null || echo 'pip não instalado'"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo ""
echo "📚 Para mais informações, consulte:"
echo "   • README.md - Documentação completa"
echo "   • INSTALL.md - Guia detalhado de instalação"
echo "   • START_HERE.md - Guia rápido de início"
echo ""
echo "💡 Dica: A opção 1 (instalar pip3) é a mais simples!"
echo ""
