# Generated by Django 5.0.14 on 2026-01-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_cidade', models.CharField(max_length=100, verbose_name='Cidade de Origem')),
                ('origem_pais', models.CharField(max_length=100, verbose_name='País de Origem')),
                ('destino_cidade', models.CharField(max_length=100, verbose_name='Cidade de Destino')),
                ('destino_pais', models.CharField(max_length=100, verbose_name='País de Destino')),
                ('tipo_carga', models.CharField(max_length=200, verbose_name='Tipo de Carga')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distância (km)')),
                ('pagamento_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pagamento (€)')),
                ('tipo_trailer', models.CharField(blank=True, choices=[('curtain', 'Curtain Side'), ('box', 'Box Trailer'), ('reefer', 'Refrigerado'), ('flatbed', 'Flatbed'), ('lowboy', 'Lowboy'), ('tanker', 'Tanque'), ('container', 'Container'), ('log', 'Madeira'), ('car_transporter', 'Cegonha')], max_length=50, null=True, verbose_name='Tipo de Trailer')),
                ('peso_toneladas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (toneladas)')),
                ('dano_percentual', models.DecimalField(decimal_places=2, default=0.0, help_text='Dano recebido durante o transporte', max_digits=5, verbose_name='Dano (%)')),
                ('combustivel_litros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Combustível (litros)')),
                ('tempo_viagem', models.DurationField(blank=True, null=True, verbose_name='Tempo de Viagem')),
                ('multas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Multas (€)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('falhada', 'Falhada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='Screenshot')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
